sveltestrap/sveltestrap

src/Container/Container.mdx
src/Grid/Grid.mdx
src/Progress/Progress.mdx
src/Spinner/Spinner.mdx

- switching source language from `jsx` to `html` to match the rest of the documentation
`pnpm start`

🧹  refactor(docs): update Component source language

---

README.md
src/DropdownItem/DropdownItem.d.ts
src/DropdownItem/DropdownItem.snap.js
src/DropdownItem/DropdownItem.svelte
src/DropdownMenu/DropdownMenu.d.ts
src/DropdownMenu/DropdownMenu.snap.js
src/DropdownMenu/DropdownMenu.svelte
src/DropdownToggle/DropdownToggle.snap.js
src/DropdownToggle/DropdownToggle.svelte

This incorporates changes from the an existing pull request in the previous sveltestrap repo.

🐛 fix(dropdown): update dropdown, dropdownitem and toggler #459

---

README.md
src/Popover/Popover.d.ts
src/Popover/Popover.mdx
src/Popover/Popover.stories.svelte
src/Popover/Popover.svelte

> Useful when `bind:isOpen` to make Popover interactive but makes it act like Bootstraps original Popover's behaviour
```jsx
<Popover bind:isOpen={isPopoverOpen} hideOnOutClick={true}> ... </Popover>
```

🐛 fix(popover): fix issue with hiding popover on outside click #418

---

.storybook/storybook.css
src/ListGroup/ListGroup.mdx
src/ListGroup/ListGroup.stories.svelte
src/ListGroup/ListGroup.svelte

- adding stories and documentation for ListGroup
`pnpm start`

📖 stories(ListGroup): add stories and documentation

---

.storybook/storybook.css
src/Tooltip/Tooltip.mdx
src/Tooltip/Tooltip.stories.svelte

- adding stories and documentation for Tooltip
- `pnpm start`

📖 stories(Tooltip): add stories and docs

---

.storybook/storybook.css
src/Carousel/Carousel.mdx
src/Carousel/Carousel.stories.svelte
src/Carousel/Carousel.svelte

- adding stories and documentation for carousel component
- `pnpm start`

stories(carousel): add stories and docs

---

.storybook/storybook.css
src/Modal/Modal.mdx
src/Modal/Modal.stories.svelte
src/Modal/Modal.svelte

- adding stories and documentation for Modal
- `pnpm start`

📖 stories(modal): add stories and docs

---

.storybook/storybook.css
src/Dropdown/Dropdown.mdx
src/Dropdown/Dropdown.stories.svelte
src/Dropdown/Dropdown.svelte

- adding stories and docs for Dropdown
- `pnpm start`

📖 stories(dropdown): add stories and docs

---

src/Alert/Alert.mdx
src/Toast/Toast.mdx
src/Toast/Toast.stories.svelte

- fixing small grammatical issues in documentation
- update Toast `status` variable to `Closed` instead of `Opened`
- `pnpm start`

🧹 refactor(docs): fix minor grammar issues

---

src/CarouselControl/CarouselControl.svelte
src/utils.js

If the carousel control had `wrap={false}` the previous navigation would never disable due to a typo `previous` should be `prev`. This fixes that issue and add some JS Doc comments to the control file.
1. Create a `<Carousel />` component
2. Set the previous nav control `<CarouselControl direction="prev" wrap={false} />` to **false**
3. Try to navigate past the first item
Reported on https://github.com/bestguy/sveltestrap/pull/536

🐛 fix(carousel): fix the disabling of previous nav when wrap has been disabled

---

.storybook/storybook.css
src/Accordion/Accordion.stories.svelte
src/Alert/Alert.mdx
src/Alert/Alert.stories.svelte
src/Badge/Badge.stories.svelte
src/Breadcrumb/Breadcrumb.stories.svelte
src/Button/Button.stories.svelte
src/Card/Card.stories.svelte
src/Carousel/Carousel.stories.svelte
src/Carousel/Carousel.svelte
src/Container/Container.stories.svelte
src/Dropdown/Dropdown.stories.svelte
src/FormGroup/FormGroup.mdx
src/FormGroup/FormGroup.stories.svelte
src/Input/Input.stories.svelte
src/InputGroup/InputGroup.stories.svelte
src/ListGroup/ListGroup.stories.svelte
src/Modal/Modal.stories.svelte
src/Nav/Nav.stories.svelte
src/Navbar/Navbar.stories.svelte
src/Offcanvas/Offcanvas.mdx
src/Offcanvas/Offcanvas.stories.svelte
src/Pagination/Pagination.stories.svelte
src/Popover/Popover.mdx
src/Popover/Popover.stories.svelte
src/Progress/Progress.stories.svelte
src/Table/Table.stories.svelte
src/Toast/Toast.mdx
src/Toast/Toast.stories.svelte
src/Tooltip/Tooltip.stories.svelte

This updates all event and slot information for each component.

📖 docs(storybook): update event and slot details

---

src/ModalHeader/ModalHeader.d.ts
src/OffcanvasHeader/OffcanvasHeader.d.ts

This adds missing properties for named slots to the interface definitions of ModalHeader and OffcanvasHeader.

🐛 fix(types): add missing slot interface properties

---

src/AccordionItem/AccordionItem.d.ts
src/Button/Button.d.ts
src/ButtonDropdown/ButtonDropdown.d.ts
src/Card/Card.d.ts
src/DropdownItem/DropdownItem.d.ts
src/Form/Form.d.ts
src/FormCheck/FormCheck.d.ts
src/Input/Input.d.ts
src/ListGroupItem/ListGroupItem.d.ts
src/ModalBackdrop/ModalBackdrop.d.ts
src/NavbarBrand/NavbarBrand.d.ts

Adds the missing event types to various components.
Closes #39

🐛 fix(types): update types with missing events

---

src/index.d.ts

Properties like `TextColor`, `ButtonColor`, etc cannot be set programmatically as these types aren't exported.
As an example, the following will not compile because `color` cannot be verified to satisfy the `color` property on `Spinner`
```svelte
<script lang="ts">
import { Spinner } from "@sveltestrap/sveltestrap";
export let size = "md";
export let color = "primary";
</script>
<div class="text-center">
<Spinner type="grow" {size} {color} />
</div>
```
```
Type 'string' is not assignable to type 'TextColor | undefined'.ts(2322)
(property) SpinnerProps.color?: TextColor | undefined
```
With this change this is now possible by using.
```svelte
<script lang="ts">
import { Spinner, type TextColor } from "@sveltestrap/sveltestrap";
export let size = "md";
export let …
```

🐛 fix(types): Export shared types to allow configurable component props with typescript.

---

src/Input/Input.d.ts
src/Input/Input.svelte
src/index.d.ts
src/shared.d.ts

This resolves an infinite loop issue with SvelteKit and Sveltestrap `input` elements 
Example:
**Select.svelte**
```svelte
<script>
export let value = '';
export let disabled = false;
</script>
<select {disabled} bind:value>
<slot></slot>
</select>
```
**App.svelte**
```svelte
<script>
import Select from './Select.svelte';
let checked = false
let selectValue = undefined;
$: if (!checked) {
console.log('Setting value to undefined')
selectValue = undefined;
}
</script>
<input type="checkbox" bind:checked />
<Select {disabled} bind:value={selectValue}>
<option />
<option value="one">One</option>
<option value="two">Two</option>
</select>
```
This results in an infinite loop with SvelteKit SSR, but works fine standalone.
Closes #47

🐛 fix(select): set input value to undefined as default to prevent binding loop with input elements

---

src/Badge/Badge.d.ts
src/Badge/Badge.mdx
src/Badge/Badge.snap.js
src/Badge/Badge.spec.js
src/Badge/Badge.stories.svelte
src/Badge/Badge.svelte
src/index.d.ts
src/shared.d.ts

These changes add support for Bootstrap positioned badges via the `<Badge>` component. The `badge` interface has new properties:
- `ariaLabel`: The text will be read by screen readers
- `border`: If set, will add a light/dark border to the badge
- `indicator`: If set, it will assign additional padding and a border to the circular marker. Needs `positioned` to be `true`
- `placement`: The CSS bootstrap classes to determine placement. This defaults to `top-0 start-100`
- `positioned`: If set, it will assign the absolute positioning classes to the `badge`
```svelte
<script lang="ts">
import { Button, Badge } from '@sveltestrap/sveltestrap';
</script>
<Button color="primary" class="position-relative">
Inbox <Badge color="danger" pill positioned ariaLabel="Unread …
```

✨ feat(badges): add positioned badge support to badges

---

src/Dropdown/Dropdown.d.ts

This fixes some incorrect typescript affecting Dropdown and ButtonDropdown.

fix(types): fix an import

---

src/Card/Card.d.ts
src/Figure/Figure.d.ts
src/Figure/Figure.svelte
src/Icon/Icon.svelte
src/Image/Image.svelte
src/Input/Input.d.ts
src/Input/Input.mdx
src/Input/Input.stories.svelte
src/Input/Input.svelte
src/InputGroup/InputGroup.svelte
src/InputGroupText/InputGroupText.svelte
src/Jumbotron/Jumbotron.svelte
src/ListGroupItem/ListGroupItem.d.ts
src/Toast/Toast.d.ts
src/Toast/Toast.svelte

This includes general cleanup of JSDoc comments and fixing types.

🧹 misc(cleanup): fixing jsdoc comments and prop types 

---

README.md
src/Input/Input.d.ts
src/Input/Input.spec.js
src/Input/Input.svelte

- Fixes a keyboard input issue with dates
- Adds a min/max to the appropriate fields
- Consolidates all the input logic
Originally reported by @StagnantIce this addresses https://github.com/bestguy/sveltestrap/issues/585 https://github.com/bestguy/sveltestrap/pull/586

🧹 refactor(input): add min/max props and dry up input logic

---

src/Input/Input.d.ts
src/Input/Input.svelte
vitest.setup.js

This modifies the input event types to address the issue mentioned #43 
Fixes #43

🐛  refactor(types): update input event types

---

src/AccordionItem/AccordionItem.d.ts
src/Collapse/Collapse.d.ts
src/Fade/Fade.d.ts

A collection of TypeScript type def fixes
#43

🐛 fix(types): update accordionItem toggle

---

src/Carousel/Carousel.svelte

This resolves an issue with the carousel, which only cycles to the second item and stops when `ride` has been enabled. The intended behavior should be that it cycles until the user hovers over the element. 
Closes #87

🐛 fix(carousel): use setInterval instead of setTimeout for cycling

---

src/Popover/Popover.d.ts
src/Popover/Popover.mdx
src/Popover/Popover.snap.js
src/Popover/Popover.spec.js
src/Popover/Popover.stories.svelte

My application needs to take advantage of the available `auto` placement to the Popover component.
Unit test has been updated.
None needed.

✨ feat(popover): adding `auto` to the PopoverPlacement type.

---

src/Figure/Figure.d.ts
src/Figure/Figure.snap.js
src/Figure/Figure.svelte

This addresses issues raised in #93.
- Removes extraneous `<img>` 
- Adds missing `class` prop to type def
- Updates component snapshot
Closes #93

🐛 fix(figure): remove extraneous image and fix type def

---

.github/workflows/integration.yml

🏗 ci(integrations): update actions/upload-artifact to v4

---

.github/workflows/integration.yml
src/Input/Input.svelte

🐛 fix(inputs): handle value coercion issue with number and range inputs
